
<b>INSTITUTO FEDERAL DE GOIÁS<br/>
PÓS-GRADUAÇÃO EM INTELIGÊNCIA ARTIFICIAL APLICADA<br/></b>
Disciplina: Modelagem e otimização aplicada  <br/>
Professor: Dr. Daywes Pinheiro Neto <br/>
Aluno: Marcos Rodrigues Brugnaro

---

#### Lista de exercícios 02
#### Resolver os problemas no Python de duas formas:
##### i) formulação padrão geral;
##### ii) formulação padrão matricial;
---
#### Questão 02

\begin{equation*}
\begin{aligned}
\text{Variáveis de decisão:} \\
\text{x1:} & & \text{quantidade de produção brinquedo A}  \\
\text{x2:} & & \text{quantidade de produção brinquedo B}  \\\\
\text{Maximizar} & & Z=10 \cdot X_1 + 15 \cdot X_2\\\\
\text{Restrições:} \\
\text{Horas de trabalho:} & & 2 \cdot X_1 + X_2 + S_0 = 80 \\
\text{Horas de máquina:} & & X_1 + 3 \cdot X_2 + S_1 = 40 \\
\text{Não-negatividade:} & & X_1, X_2, S_0, S_1 \geq 0 \\
\end{aligned}
\end{equation*}

In [1]:
from cvxopt.modeling import op, variable
from plotly import graph_objects as go

In [2]:
brinq_a = variable(1, 'quantidade de produção brinquedo A')
brinq_b = variable(1, 'quantidade de produção brinquedo B')
folga = variable(2, 'Variável de folga')

In [3]:
fob = - 10 * brinq_a[0] - 15 * brinq_b[0]

In [4]:
restricoes = []
restricoes.append(2 * brinq_a[0] + brinq_b[0] + folga[0] == 80)
restricoes.append(brinq_a[0] + 3 * brinq_b[0] + folga[1] == 40)
restricoes.append(brinq_a[0] >= 0)
restricoes.append(brinq_b[0] >= 0)
restricoes.append(folga[0] >= 0)
restricoes.append(folga[1] >= 0)

In [5]:
fabrica = op(fob, restricoes)
fabrica.solve('dense', 'glpk')

In [6]:
print(f'Lucro projetado para a fábrica de brinquedos é de ${-fob.value()[0]:.2f}')
print(f'{brinq_a.name} é de {brinq_a[0].value()[0]}')
print(f'{brinq_b.name} é de {brinq_b[0].value()[0]}')

Lucro projetado para a fábrica de brinquedos é de $400.00
quantidade de produção brinquedo A é de 40.0
quantidade de produção brinquedo B é de 0.0


In [7]:
print('Variável dual associado ao limite de horas de trabalho', restricoes[0].multiplier.value)
print('Variável dual associado ao limite de horas de máquina', restricoes[1].multiplier.value)
print('Variável dual associado ao limite de não-negatividade brinquedo A (x1)', restricoes[2].multiplier.value)
print('Variável dual associado ao limite de não-negatividade brinquedo B (x2)', restricoes[2].multiplier.value)

Variável dual associado ao limite de horas de trabalho [ 3.00e+00]

Variável dual associado ao limite de horas de máquina [ 4.00e+00]

Variável dual associado ao limite de não-negatividade brinquedo A (x1) [ 0.00e+00]

Variável dual associado ao limite de não-negatividade brinquedo B (x2) [ 0.00e+00]



In [ ]:
figura = go.Figure(data=go.Bar(y=[brinq_a[0].value()[0], brinq_b[0].value()[0]], x=['brinquedo_a','brinquedo_b']))
figura.show()

In [ ]:
from cvxopt import matrix, solvers
import numpy as np

In [ ]:
c = matrix([-10.0, -15.0, 0.0, 0.0])
Aeq = matrix([[2.0, 1.0, 1.0, 0.0], [1.0, 3.0, 0.0, 1.0]], (2,4), 'd')
beq = matrix([800.0, 2400.0])

G = matrix(-np.eye(4))
h = matrix(np.zeros(4))

print(G)

sol = solvers.lp(c, G, h, Aeq, beq)
print(sol['x'])

[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]

     pcost       dcost       gap    pres   dres   k/t
 0:  1.9512e+02  1.9512e+02  9e+03  2e+02  9e-01  1e+00
 1: -6.1216e+03 -5.4427e+03  5e+04  3e+02  2e+00  7e+02
 2: -8.1649e+03 -7.6578e+03  4e+03  3e+01  2e-01  5e+02
 3: -1.1949e+04 -1.1899e+04  1e+02  9e-01  5e-03  5e+01
 4: -1.1999e+04 -1.1999e+04  1e+00  9e-03  5e-05  5e-01
 5: -1.2000e+04 -1.2000e+04  1e-02  9e-05  5e-07  5e-03
 6: -1.2000e+04 -1.2000e+04  1e-04  9e-07  5e-09  5e-05
 7: -1.2000e+04 -1.2000e+04  1e-06  9e-09  5e-11  5e-07
Optimal solution found.
[ 1.42e-09]
[ 8.00e+02]
[ 3.23e-08]
[ 2.40e+03]

