
<b>INSTITUTO FEDERAL DE GOIÁS<br/>
PÓS-GRADUAÇÃO EM INTELIGÊNCIA ARTIFICIAL APLICADA<br/></b>
Disciplina: Modelagem e otimização aplicada  <br/>
Professor: Dr. Daywes Pinheiro Neto <br/>
Aluno: Marcos Rodrigues Brugnaro

---

#### Lista de exercícios 02
#### Resolver os problemas no Python de duas formas:
##### i) formulação padrão geral;
##### ii) formulação padrão matricial;
---
#### Questão 04

\begin{equation*}
\begin{aligned}
\text{Variáveis de decisão:} \\
\text{x1:} & & \text{quantidade de compra de caminhões grandes}  \\
\text{x2:} & & \text{quantidade de  compra de caminhões pequenos}  \\\\
\text{Maximizar} & & Z=5 \cdot X_1 + 4 \cdot X_2\\\\
\text{Restrições:} \\
\text{Orçamento:} & & 50000 \cdot X_1 + 30000 \cdot X_2 + S_0 = 200000 \\
\text{Toneladas de mercadoria:} & & 10 \cdot X_1 + 5 \cdot X_2 + S_1 = 30 \\
\text{Não-negatividade:} & & X_1, X_2, S_0, S_1 \geq 0 \\
\end{aligned}
\end{equation*}

In [1]:
from cvxopt.modeling import op, variable
from plotly import graph_objects as go

In [2]:
cam_grande = variable(1, 'quantidade de compra de caminhões grandes')
cam_peq = variable(1, 'quantidade de  compra de caminhões pequenos')
folga = variable(2, 'Variável de folga')

In [3]:
fob = - 5 * cam_grande[0] - 4 * cam_peq[0]

In [4]:
restricoes = []

restricoes.append(50000 * cam_grande[0] + 30000 * cam_peq[0] + folga[0] == 200000)
restricoes.append(10 * cam_grande[0] + 5 * cam_peq[0] + folga[1] == 30)
restricoes.append(cam_grande[0] >= 0)
restricoes.append(cam_peq[0] >= 0)
restricoes.append(folga[0] >= 0)
restricoes.append(folga[1] >= 0)

In [5]:
empresa_transporte = op(fob, restricoes)
empresa_transporte.solve('dense', 'glpk')

In [6]:
print(f'Lucro projetado para empresa de transporte é de ${-fob.value()[0]:.2f}')
print(f'{cam_grande.name} é de {cam_grande[0].value()[0]}')
print(f'{cam_peq.name} é de {cam_peq[0].value()[0]}')

Lucro projetado para empresa de transporte é de $24.00
quantidade de compra de caminhões grandes é de 0.0
quantidade de  compra de caminhões pequenos é de 6.0


In [7]:
print('Variável dual associado ao limite de orçamento', restricoes[0].multiplier.value)
print('Variável dual associado ao limite de toneladas de mercadoria', restricoes[1].multiplier.value)
print('Variável dual associado ao limite de não-negatividade caminhões grandes (x1)', restricoes[2].multiplier.value)
print('Variável dual associado ao limite de não-negatividade caminhões pequenos (x2)', restricoes[2].multiplier.value)

Variável dual associado ao limite de orçamento [ 0.00e+00]

Variável dual associado ao limite de toneladas de mercadoria [ 8.00e-01]

Variável dual associado ao limite de não-negatividade caminhões grandes (x1) [ 3.00e+00]

Variável dual associado ao limite de não-negatividade caminhões pequenos (x2) [ 3.00e+00]



In [ ]:
figura = go.Figure(data=go.Bar(y=[cam_grande[0].value()[0], cam_peq[0].value()[0]], x=['caminhao_grande','caminhao_pequeno']))
figura.show()

In [ ]:
from cvxopt import matrix, solvers
import numpy as np

In [ ]:
c = matrix([-5.0, -4.0, 0.0, 0.0])

Aeq = matrix([
    [50000.0, 30000.0, 1.0, 0.0],
    [10.0, 5.0, 0.0, 1.0]], (2,4), 'd')

beq = matrix([200000.0, 30.0])

G = matrix(-np.eye(4))
h = matrix(np.zeros(4))

print(G)

sol = solvers.lp(c, G, h, Aeq, beq)
print(sol['x'])

[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]

     pcost       dcost       gap    pres   dres   k/t
 0: -1.2197e+05 -1.2197e+05  9e+05  1e+05  1e+00  1e+00
 1: -4.0245e+05 -3.8169e+05  8e+05  7e+04  1e+00  2e+04
 2:  1.2271e+07  1.8353e+07  8e+09  7e+06  1e+02  6e+06
 3: -1.2416e+06  1.6202e+05  1e+08  1e+05  2e+00  1e+06
 4: -6.9124e+07  3.9891e+05  7e+09  2e+05  3e+00  7e+07
 5: -2.1162e+10  4.6815e+07  4e+13  1e+07  1e+02  2e+10
 6: -2.7171e+09  1.2662e+06  4e+10  2e+05  3e+00  3e+09
 7: -6.7360e+09 -1.7313e+04  4e+10  9e+04  1e+00  7e+09
 8: -7.3522e+07 -8.2208e+05  2e+09  3e+03  4e-02  7e+07
 9: -1.5781e+06 -8.4644e+05  2e+07  3e+01  4e-04  7e+05
10: -8.1834e+05 -8.1135e+05  4e+05  7e-01  1e-05  7e+03
11: -8.0091e+05 -8.0084e+05  2e+04  4e-02  5e-07  7e+01
12: -8.0017e+05 -8.0009e+05  4e+02  5e-03  7e-08  9e+01
13: -8.0000e+05 -8.0000e+05  5e+00  6e-05  8e-10 