
<b>INSTITUTO FEDERAL DE GOIÁS<br/>
PÓS-GRADUAÇÃO EM INTELIGÊNCIA ARTIFICIAL APLICADA<br/></b>
Disciplina: Modelagem e otimização aplicada  <br/>
Professor: Dr. Daywes Pinheiro Neto <br/>
Aluno: Marcos Rodrigues Brugnaro

---

#### Lista de exercícios 02
#### Resolver os problemas no Python de duas formas:
##### i) formulação padrão geral;
##### ii) formulação padrão matricial;
---
#### Questão 06

\begin{equation*}
\begin{aligned}
\text{Variáveis de decisão:} \\
\text{x1:} & & \text{quantidade de produção de sopa A}  \\
\text{x2:} & & \text{quantidade de produção de sopa B}  \\\\
\text{Maximizar} & & Z=3 \cdot X_1 + 4 \cdot X_2\\\\
\text{Restrições:} \\
\text{Litros de água:} & & 4 \cdot X_1 + 3 \cdot X_2 + S_0 = 500 \\
\text{Tomates:} & & 2 \cdot X_1 + 2 \cdot X_2 + S_1 = 300 \\
\text{Cenouras:} & & X_1 + 2 \cdot X_2 + S_2 = 250 \\
\text{Não-negatividade:} & & X_1, X_2, S_0, S_1, S_2 \geq 0 \\
\end{aligned}
\end{equation*}

In [1]:
from cvxopt.modeling import op, variable
from plotly import graph_objects as go

In [6]:
sopa_a = variable(1, 'quantidade de produção de sopa A')
sopa_b = variable(1, 'quantidade de produção de sopa B')
folga = variable(3, 'Variável de folga')

In [7]:
fob = - 3 * sopa_a[0] - 4 * sopa_b[0]

In [8]:
restricoes = []

restricoes.append(4 * sopa_a[0] + 3 * sopa_b[0] + folga[0] == 500)
restricoes.append(2 * sopa_a[0] + 2 * sopa_b[0] + folga[1] == 300)
restricoes.append(sopa_a[0] + 2 * sopa_b[0] + folga[2] == 250)
restricoes.append(sopa_a[0] >= 0)
restricoes.append(sopa_b[0] >= 0)
restricoes.append(folga[0] >= 0)
restricoes.append(folga[1] >= 0)
restricoes.append(folga[2] >= 0)

In [9]:
empresa_alimentos = op(fob, restricoes)
empresa_alimentos.solve('dense', 'glpk')

In [10]:
print(f'Lucro projetado para empresa de alimentos é de ${-fob.value()[0]:.2f}')
print(f'{sopa_a.name} é de {sopa_a[0].value()[0]}')
print(f'{sopa_b.name} é de {sopa_b[0].value()[0]}')

Lucro projetado para empresa de alimentos é de $550.00
quantidade de produção de sopa A é de 50.0
quantidade de produção de sopa B é de 100.0


In [11]:
print('Variável dual associado ao limite de litros de água', restricoes[0].multiplier.value)
print('Variável dual associado ao limite de tomates', restricoes[1].multiplier.value)
print('Variável dual associado ao limite de cenouras', restricoes[2].multiplier.value)
print('Variável dual associado ao limite de não-negatividade da sopa A (x1)', restricoes[2].multiplier.value)
print('Variável dual associado ao limite de não-negatividade da sopa B (x2)', restricoes[2].multiplier.value)

Variável dual associado ao limite de litros de água [ 4.00e-01]

Variável dual associado ao limite de tomates [ 0.00e+00]

Variável dual associado ao limite de cenouras [ 1.40e+00]

Variável dual associado ao limite de não-negatividade da sopa A (x1) [ 1.40e+00]

Variável dual associado ao limite de não-negatividade da sopa B (x2) [ 1.40e+00]



In [12]:
figura = go.Figure(data=go.Bar(y=[sopa_a[0].value()[0], sopa_b[0].value()[0]], x=['sopa_a','sopa_b']))
figura.show()

In [13]:
from cvxopt import matrix, solvers
import numpy as np

In [14]:
c = matrix([-3.0, -4.0, 0.0, 0.0, 0.0])

Aeq = matrix([[4.0, 3.0, 1.0, 0.0, 0.0],
              [2.0, 2.0, 0.0, 1.0, 0.0],
              [1.0, 2.0, 0.0, 0.0, 1.0],
              ], (3,5), 'd')

beq = matrix([500.0, 300.0, 250.0])

G = matrix(-np.eye(5))
h = matrix(np.zeros(5))

print(G)

sol = solvers.lp(c, G, h, Aeq, beq)
print(sol['x'])

[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]

     pcost       dcost       gap    pres   dres   k/t
 0: -3.7647e+02 -3.7647e+02  7e+02  9e-17  2e+00  1e+00
 1: -4.8740e+02 -4.7826e+02  2e+02  3e-14  4e-01  9e+00
 2: -4.9874e+02 -4.9855e+02  4e+00  2e-14  1e-02  2e-01
 3: -4.9999e+02 -4.9999e+02  4e-02  2e-14  1e-04  2e-03
 4: -5.0000e+02 -5.0000e+02  4e-04  3e-16  1e-06  2e-05
 5: -5.0000e+02 -5.0000e+02  4e-06  4e-14  1e-08  2e-07
Optimal solution found.
[ 1.00e+02]
[ 5.00e+01]
[ 5.00e+01]
[ 3.85e-09]
[ 6.18e-07]

