
<b>INSTITUTO FEDERAL DE GOIÁS<br/>
PÓS-GRADUAÇÃO EM INTELIGÊNCIA ARTIFICIAL APLICADA<br/></b>
Disciplina: Modelagem e otimização aplicada  <br/>
Professor: Dr. Daywes Pinheiro Neto <br/>
Aluno: Marcos Rodrigues Brugnaro

---

#### Lista de exercícios 02
#### Resolver os problemas no Python de duas formas:
##### i) formulação padrão geral;
##### ii) formulação padrão matricial;
---
#### Questão 01

\begin{equation*}
\begin{aligned}
\text{Variáveis de decisão:} \\
\text{x1:} & & \text{quantidade de acres de milho plantar}  \\
\text{x2:} & & \text{quantidade de acres de trigo plantar}  \\\\
\text{Maximizar} & & Z=70 \cdot X_1 + 50 \cdot X_2\\\\
\text{Restrições:} \\
\text{Horas de trabalho:} & & 2 \cdot X_1 + X_2 + S_0 = 800 \\
\text{Orçamento:} & & 40 \cdot X_1 + 30 \cdot X_2 + S_1 = 2.400 \\
\text{Não-negatividade:} & & X_1, X_2, S_0, S_1 \geq 0 \\
\end{aligned}
\end{equation*}

In [1]:
from cvxopt.modeling import op, variable
from plotly import graph_objects as go

In [2]:
milho = variable(1, 'Quantidade de acres de milho plantar')
trigo = variable(1, 'Quantidade de acres de trigo plantar')
folga = variable(2, 'Variável de folga')

In [3]:
fob = - 70 * milho[0] - 50 * trigo[0]

In [4]:
restricoes = []
restricoes.append(2 * milho[0] + trigo[0] + folga[0] == 800)
restricoes.append(40 * milho[0] + 30 * trigo[0] + folga[1] == 2400)
restricoes.append(milho[0] >= 0)
restricoes.append(trigo[0] >= 0)
restricoes.append(folga[0] >= 0)
restricoes.append(folga[1] >= 0)

In [5]:
fazendeiro = op(fob, restricoes)
fazendeiro.solve('dense', 'glpk')

In [6]:
print(f'Lucro projetado para o fazendeiro é de ${-fob.value()[0]:.2f}')
print(f'{milho.name} é de {milho[0].value()[0]}')
print(f'{trigo.name} é de {trigo[0].value()[0]}')

Lucro projetado para o fazendeiro é de $4200.00
Quantidade de acres de milho plantar é de 60.0
Quantidade de acres de trigo plantar é de 0.0


In [7]:
print('Variável dual associado ao limite de horas de trabalho', restricoes[0].multiplier.value)
print('Variável dual associado ao limite de orçamento', restricoes[1].multiplier.value)
print('Variável dual associado ao limite de não-negatividade milho (x1)', restricoes[2].multiplier.value)
print('Variável dual associado ao limite de não-negatividade trigo (x2)', restricoes[2].multiplier.value)

Variável dual associado ao limite de horas de trabalho [ 0.00e+00]

Variável dual associado ao limite de orçamento [ 1.75e+00]

Variável dual associado ao limite de não-negatividade milho (x1) [ 0.00e+00]

Variável dual associado ao limite de não-negatividade trigo (x2) [ 0.00e+00]



In [8]:
figura = go.Figure(data=go.Bar(y=[milho[0].value()[0], trigo[0].value()[0]], x=['Milho','Trigo']))
figura.show()

In [ ]:
from cvxopt import matrix, solvers
import numpy as np

In [ ]:
c = matrix([-70.0, -50.0, 0.0, 0.0])
Aeq = matrix([[2.0, 1.0, 1.0, 0.0], [40.0, 30.0, 0.0, 1.0]], (2,4), 'd')
beq = matrix([800.0, 2400.0])

G = matrix(-np.eye(4))
h = matrix(np.zeros(4))

print(G)

sol = solvers.lp(c, G, h, Aeq, beq)
print(sol['x'])

[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]

     pcost       dcost       gap    pres   dres   k/t
 0:  7.1810e+04  7.1810e+04  6e+04  1e+03  1e+00  1e+00
 1: -6.7727e+04 -6.7464e+04  8e+05  2e+03  2e+00  3e+02
 2: -1.5968e+04 -8.9228e+03  6e+05  2e+03  1e+00  7e+03
 3: -9.6703e+06 -6.4958e+06  5e+09  1e+05  1e+02  3e+06
 4: -2.4157e+05  1.0492e+05  2e+06  2e+03  2e+00  3e+05
 5: -2.9775e+05 -3.6250e+04  4e+05  4e+02  3e-01  3e+05
 6: -5.6082e+04 -5.3857e+04  5e+04  3e+01  3e-02  2e+03
 7: -4.1010e+04 -3.9966e+04  6e+03  6e+00  5e-03  1e+03
 8: -4.0076e+04 -4.0045e+04  1e+02  1e-01  1e-04  3e+01
 9: -4.0001e+04 -4.0000e+04  1e+00  1e-03  1e-06  3e-01
10: -4.0000e+04 -4.0000e+04  1e-02  1e-05  1e-08  3e-03
11: -4.0000e+04 -4.0000e+04  1e-04  1e-07  1e-10  3e-05
12: -4.0000e+04 -4.0000e+04  1e-06  1e-09  1e-12  3e-07
Optimal solution found.
[ 1.50e-08]
[ 8.00e+02]
[