
<b>INSTITUTO FEDERAL DE GOIÁS<br/>
PÓS-GRADUAÇÃO EM INTELIGÊNCIA ARTIFICIAL APLICADA<br/></b>
Disciplina: Modelagem e otimização aplicada  <br/>
Professor: Dr. Daywes Pinheiro Neto <br/>
Aluno: Marcos Rodrigues Brugnaro

---

#### Lista de exercícios 02
#### Resolver os problemas no Python de duas formas:
##### i) formulação padrão geral;
##### ii) formulação padrão matricial;
---
#### Questão 03

\begin{equation*}
\begin{aligned}
\text{Variáveis de decisão:} \\
\text{x1:} & & \text{quantidade de mesas produzidas}  \\
\text{x2:} & & \text{quantidade de cadeiras produzidas}  \\\\
\text{Maximizar} & & Z=200 \cdot X_1 + 100 \cdot X_2\\\\
\text{Restrições:} \\
\text{Metros de madeira:} & & 4 \cdot X_1 + 2 \cdot X_2 + S_0 = 800 \\
\text{Horas de mão de obra:} & & 2 \cdot X_1 + X_2 + S_1 = 400 \\
\text{Não-negatividade:} & & X_1, X_2, S_0, S_1 \geq 0 \\
\end{aligned}
\end{equation*}

In [1]:
from cvxopt.modeling import op, variable
from plotly import graph_objects as go

In [2]:
mesa = variable(1, 'quantidade de mesas produzidas')
cadeira = variable(1, 'quantidade de cadeiras produzidas')
folga = variable(2, 'Variável de folga')

In [3]:
fob = - 200 * mesa[0] - 100 * cadeira[0]

In [4]:
restricoes = []

restricoes.append(4 * mesa[0] + 2 * cadeira[0] + folga[0] == 800)
restricoes.append(2 * mesa[0] + cadeira[0] + folga[1] == 400)
restricoes.append(mesa[0] >= 0)
restricoes.append(cadeira[0] >= 0)
restricoes.append(folga[0] >= 0)
restricoes.append(folga[1] >= 0)

In [5]:
empresa = op(fob, restricoes)
empresa.solve('dense', 'glpk')

In [6]:
print(f'Lucro projetado para empresa é de ${-fob.value()[0]:.2f}')
print(f'{mesa.name} é de {mesa[0].value()[0]}')
print(f'{cadeira.name} é de {cadeira[0].value()[0]}')

Lucro projetado para empresa é de $40000.00
quantidade de mesas produzidas é de 200.0
quantidade de cadeiras produzidas é de 0.0


In [7]:
print('Variável dual associado ao limite de metros de madeira', restricoes[0].multiplier.value)
print('Variável dual associado ao limite de horas de mão de obra', restricoes[1].multiplier.value)
print('Variável dual associado ao limite de não-negatividade mesa (x1)', restricoes[2].multiplier.value)
print('Variável dual associado ao limite de não-negatividade cadeira (x2)', restricoes[2].multiplier.value)

Variável dual associado ao limite de metros de madeira [ 5.00e+01]

Variável dual associado ao limite de horas de mão de obra [ 0.00e+00]

Variável dual associado ao limite de não-negatividade mesa (x1) [ 0.00e+00]

Variável dual associado ao limite de não-negatividade cadeira (x2) [ 0.00e+00]



In [ ]:
figura = go.Figure(data=go.Bar(y=[mesa[0].value()[0], cadeira[0].value()[0]], x=['mesa','cadeira']))
figura.show()

In [ ]:
from cvxopt import matrix, solvers
import numpy as np

In [ ]:
c = matrix([-200.0, -100.0, 0.0, 0.0])

Aeq = matrix([
    [4.0, 2.0, 1.0, 0.0],
    [2.0, 1.0, 0.0, 1.0]], (2,4), 'd')

beq = matrix([800.0, 400.0])

G = matrix(-np.eye(4))
h = matrix(np.zeros(4))

print(G)

sol = solvers.lp(c, G, h, Aeq, beq)
print(sol['x'])

[-1.00e+00 -0.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -0.00e+00 -1.00e+00]

     pcost       dcost       gap    pres   dres   k/t
 0: -3.3846e+04 -3.3846e+04  1e+04  3e-16  4e-01  1e+00
 1: -3.6754e+04 -3.5739e+04  7e+04  1e-13  8e-01  1e+03
 2: -6.4350e+04 -6.3779e+04  3e+04  1e-13  2e-01  6e+02
 3: -7.9790e+04 -7.9747e+04  4e+02  1e-13  4e-03  4e+01
 4: -7.9998e+04 -7.9997e+04  4e+00  1e-13  4e-05  4e-01
 5: -8.0000e+04 -8.0000e+04  4e-02  2e-13  4e-07  4e-03
 6: -8.0000e+04 -8.0000e+04  4e-04  1e-13  4e-09  4e-05
Optimal solution found.
[ 1.53e-07]
[ 8.00e+02]
[ 8.99e-07]
[ 4.00e+02]

