
<b>INSTITUTO FEDERAL DE GOIÁS<br/>
PÓS-GRADUAÇÃO EM INTELIGÊNCIA ARTIFICIAL APLICADA<br/></b>
Disciplina: Modelagem e otimização aplicada  <br/>
Professor: Dr. Daywes Pinheiro Neto <br/>
Aluno: Marcos Rodrigues Brugnaro

---

#### Lista de exercícios 02
#### Resolver os problemas no Python de duas formas:
##### i) formulação padrão geral;
##### ii) formulação padrão matricial;
---
#### Questão 05

\begin{equation*}
\begin{aligned}
\text{Variáveis de decisão:} \\
\text{x1:} & & \text{quantidade de vendas produto A}  \\
\text{x2:} & & \text{quantidade de vendas produto B}  \\\\
\text{Maximizar} & & Z=3 \cdot X_1 + 5 \cdot X_2\\\\
\text{Restrições:} \\
\text{m² de espaço de prateleira:} & & 2 \cdot X_1 + 3 \cdot X_2 + S_0 = 60 \\
\text{Não-negatividade:} & & X_1, X_2, S_0 \geq 0 \\
\end{aligned}
\end{equation*}

In [1]:
from cvxopt.modeling import op, variable
from plotly import graph_objects as go

In [2]:
prod_a = variable(1, 'quantidade de vendas produto A')
prod_b = variable(1, 'quantidade de vendas produto B')
folga = variable(1, 'Variável de folga')

In [3]:
fob = - 3 * prod_a[0] - 5 * prod_b[0]

In [4]:
restricoes = []

restricoes.append(2 * prod_a[0] + 3 * prod_b[0] + folga[0] == 60)
restricoes.append(prod_a[0] >= 0)
restricoes.append(prod_b[0] >= 0)
restricoes.append(folga[0] >= 0)

In [5]:
loja = op(fob, restricoes)
loja.solve('dense', 'glpk')

In [6]:
print(f'Lucro projetado para loja é de ${-fob.value()[0]:.2f}')
print(f'{prod_a.name} é de {prod_a[0].value()[0]}')
print(f'{prod_b.name} é de {prod_b[0].value()[0]}')

Lucro projetado para loja é de $100.00
quantidade de vendas produto A é de 0.0
quantidade de vendas produto B é de 20.0


In [7]:
print('Variável dual associado ao limite de m² de espaço de prateleira', restricoes[0].multiplier.value)
print('Variável dual associado ao limite de não-negatividade produto A (x1)', restricoes[2].multiplier.value)
print('Variável dual associado ao limite de não-negatividade produto B (x2)', restricoes[2].multiplier.value)

Variável dual associado ao limite de m² de espaço de prateleira [ 1.67e+00]

Variável dual associado ao limite de não-negatividade produto A (x1) [ 0.00e+00]

Variável dual associado ao limite de não-negatividade produto B (x2) [ 0.00e+00]



In [ ]:
figura = go.Figure(data=go.Bar(y=[prod_a[0].value()[0], prod_b[0].value()[0]], x=['produto_a','produto_b']))
figura.show()

In [ ]:
from cvxopt import matrix, solvers
import numpy as np

In [ ]:
c = matrix([-3.0, -5.0, 0.0])

Aeq = matrix([[2.0, 3.0, 1.0]], (1,3), 'd')

beq = matrix([60.0])

G = matrix(-np.eye(3))
h = matrix(np.zeros(3))

print(G)

sol = solvers.lp(c, G, h, Aeq, beq)
print(sol['x'])

[-1.00e+00 -0.00e+00 -0.00e+00]
[-0.00e+00 -1.00e+00 -0.00e+00]
[-0.00e+00 -0.00e+00 -1.00e+00]

     pcost       dcost       gap    pres   dres   k/t
 0: -9.0000e+01 -9.0000e+01  4e+01  1e-16  4e-01  1e+00
 1: -9.6664e+01 -9.6641e+01  4e+00  2e-15  5e-02  1e-01
 2: -9.9959e+01 -9.9942e+01  8e-02  4e-15  1e-03  2e-02
 3: -1.0000e+02 -9.9999e+01  8e-04  3e-15  1e-05  2e-04
 4: -1.0000e+02 -1.0000e+02  8e-06  6e-15  1e-07  2e-06
 5: -1.0000e+02 -1.0000e+02  8e-08  3e-15  1e-09  2e-08
Optimal solution found.
[ 4.96e-08]
[ 2.00e+01]
[ 1.49e-08]

